const products = [
    {
        id: 1,
        name: 'Trailblazer Sneakers',
        description: 'Lightweight and durable trail-running shoes.',
        price: 34.99,
        imageUrl: '/p1.png',
        innerdescription: 'The Trailblazer Sneakers are designed for runners who want to take their training off-road. These lightweight and durable shoes are perfect for trail running, hiking, and other outdoor activities. The Trailblazer Sneakers feature a rugged outsole with deep lugs for excellent traction on a variety of surfaces. The upper is made from breathable mesh and synthetic materials that provide support and protection without adding extra weight. With a cushioned midsole and a comfortable fit, the Trailblazer Sneakers are ready to take on any adventure.',
    },
    {
        id: 2,
        name: 'Urban Glide',
        description: 'Comfortable sneakers for daily wear.',
        innerdescription: 'The Urban Glide sneakers are designed for everyday comfort and style. These versatile shoes are perfect for running errands, going for walks, or just hanging out with friends. The Urban Glide sneakers feature a lightweight and breathable upper that keeps your feet cool and comfortable all day long. The cushioned midsole provides support and shock absorption, while the durable outsole offers traction and stability on a variety of surfaces. With a sleek design and a comfortable fit, the Urban Glide sneakers are the perfect choice for any casual occasion.',
        price: 23.49,
        imageUrl: '/p2.png',
    },
    {
        id: 3,
        name: 'Pro Runner 3000',
        description: 'High-performance shoes for serious runners.',
        innerdescription: 'The Pro Runner 3000 is a high-performance running shoe designed for serious runners who want to take their training to the next level. These shoes feature a lightweight and breathable upper that provides support and stability without adding extra weight. The cushioned midsole offers excellent shock absorption and energy return, while the durable outsole provides traction and durability on a variety of surfaces. With a sleek design and a comfortable fit, the Pro Runner 3000 is the perfect choice for runners who want to go the distance.',
        price: 45.99,
        imageUrl: '/p3.png',
    },
    {
        id: 4,
        name: 'Classic Comfort',
        description: 'Timeless design with modern cushioning.',
        innerdescription: 'The Classic Comfort shoes combine timeless design with modern cushioning for a comfortable and stylish look. These shoes feature a durable upper with a classic lace-up design that provides a secure fit. The cushioned midsole offers support and shock absorption, while the durable outsole provides traction and stability on a variety of surfaces. With a sleek design and a comfortable fit, the Classic Comfort shoes are the perfect choice for any casual occasion.',
        price: 28.79,
        imageUrl: '/p4.png',
    },
    {
        id: 5,
        name: 'Elite Walkers',
        description: 'Perfect for long walks and all-day comfort.',
        innerdescription: 'The Elite Walkers are designed for long walks and all-day comfort. These shoes feature a lightweight and breathable upper that keeps your feet cool and comfortable, while the cushioned midsole provides support and shock absorption. The durable outsole offers traction and stability on a variety of surfaces, making the Elite Walkers the perfect choice for any walking adventure. With a sleek design and a comfortable fit, these shoes are sure to become your go-to pair for all your walking needs.',
        price: 31.99,
        imageUrl: '/p5.png',
    },
    {
        id: 6,
        name: 'Peak Performers',
        description: 'Engineered for peak athletic performance.',
        innerdescription: 'The Peak Performers are engineered for peak athletic performance. These shoes feature a lightweight and breathable upper that provides support and stability without adding extra weight. The cushioned midsole offers excellent shock absorption and energy return, while the durable outsole provides traction and durability on a variety of surfaces. With a sleek design and a comfortable fit, the Peak Performers are the perfect choice for athletes who want to take their training to the next level.',
        price: 41.29,
        imageUrl: '/p6.png',
    },
    {
        id: 7,
        name: 'Street Vibe',
        description: 'Stylish shoes for a bold urban look.',
        innerdescription: 'The Street Vibe shoes are designed for individuals who want to make a bold statement. These stylish shoes combine a modern aesthetic with all-day comfort, making them perfect for urban settings. With a breathable upper and a supportive midsole, the Street Vibe shoes ensure a comfortable fit while keeping you on trend.',
        price: 25.99,
        imageUrl: '/p7.png',
    },
    {
        id: 8,
        name: 'All-Terrain Explorers',
        description: 'Built to handle any terrain with ease.',
        innerdescription: 'The All-Terrain Explorers are your ultimate companion for outdoor adventures. These rugged shoes are equipped with a durable outsole that provides excellent traction on any terrain, while the cushioned midsole ensures comfort throughout your journey. Whether hiking, trekking, or exploring new trails, these shoes will keep you steady and supported.',
        price: 38.49,
        imageUrl: '/p8.png',
    },
    {
        id: 9,
        name: 'Power Step',
        description: 'Shoes designed for strength and durability.',
        innerdescription: 'The Power Step shoes are built to withstand the toughest challenges. Featuring a reinforced upper and a sturdy outsole, these shoes are perfect for heavy-duty activities. The cushioned midsole provides support and shock absorption, ensuring comfort even during intense workouts or long hours on your feet.',
        price: 44.99,
        imageUrl: '/p9.png',
    },
    {
        id: 10,
        name: 'Casual Stride',
        description: 'Everyday shoes for relaxed comfort.',
        innerdescription: 'The Casual Stride shoes are ideal for those who value simplicity and comfort. These versatile shoes feature a soft and breathable upper, ensuring a comfortable fit for all-day wear. With a lightweight design and a durable outsole, they are perfect for casual outings and everyday activities.',
        price: 29.59,
        imageUrl: '/p10.png',
    },
    {
        id: 11,
        name: 'Velocity Boost',
        description: 'Shoes for enhanced speed and agility.',
        innerdescription: 'The Velocity Boost shoes are designed to help you move faster and more efficiently. Featuring a lightweight and aerodynamic design, these shoes provide excellent support and energy return. Perfect for runners and athletes, the Velocity Boost shoes will help you achieve your performance goals.',
        price: 20.49,
        imageUrl: '/p11.png',
    },
    {
        id: 12,
        name: 'Comfy Cloud',
        description: 'Soft and plush shoes for all-day wear.',
        innerdescription: 'The Comfy Cloud shoes are as soft and plush as their name suggests. With a memory foam insole and a cushioned midsole, these shoes provide unmatched comfort for all-day wear. Whether lounging at home or running errands, the Comfy Cloud shoes are the ultimate in relaxation.',
        price: 36.79,
        imageUrl: '/p12.png',
    },
    {
        id: 13,
        name: 'Stamina Edge',
        description: 'Built to go the extra mile.',
        innerdescription: 'The Stamina Edge shoes are designed for endurance and resilience. With a durable outsole and a supportive midsole, these shoes can handle long distances and intense activities. The breathable upper ensures comfort, while the sleek design keeps you looking sharp.',
        price: 42.99,
        imageUrl: '/p13.png',
    },
    {
        id: 14,
        name: 'Mountain Climber',
        description: 'Shoes for outdoor adventures and hiking.',
        innerdescription: 'The Mountain Climber shoes are made for outdoor enthusiasts. Featuring a rugged design and excellent grip, these shoes are ideal for hiking and exploring challenging terrains. The cushioned midsole and reinforced upper provide both comfort and durability for your adventures.',
        price: 48.99,
        imageUrl: '/p14.png',
    },
    {
        id: 15,
        name: 'Swift Motion',
        description: 'Designed for speed and quick transitions.',
        innerdescription: 'The Swift Motion shoes are perfect for those who value speed and agility. Featuring a lightweight upper and a responsive midsole, these shoes are designed to keep up with your fast-paced lifestyle. Whether training or on the go, the Swift Motion shoes deliver exceptional performance and comfort.',
        price: 26.49,
        imageUrl: '/p15.png',
    },   
    
];

export default products;
